/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import java.awt.Color;

/**
 *
 * @author oscar
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelInfo
     */
    public PanelControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hawkins = new javax.swing.JLabel();
        Portales = new javax.swing.JLabel();
        UpsideDown = new javax.swing.JLabel();
        Capturas = new javax.swing.JLabel();
        EventoActual = new javax.swing.JLabel();
        jPanelHawkins = new javax.swing.JPanel();
        NinosEnHawkins = new javax.swing.JLabel();
        jPanelNinosHawkins = new javax.swing.JPanel();
        numNinosHawkins = new javax.swing.JLabel();
        jPanelPortales = new javax.swing.JPanel();
        EstadoActual = new javax.swing.JLabel();
        Laboratorio = new javax.swing.JLabel();
        CentroComercial = new javax.swing.JLabel();
        Bosque = new javax.swing.JLabel();
        Alcantarillado = new javax.swing.JLabel();
        jPanelNinosPortalLaboratorio = new javax.swing.JPanel();
        numNinosPortalLaboratorio = new javax.swing.JLabel();
        jPanelNinosPortalCentroComercial = new javax.swing.JPanel();
        numNinosPortalCentroComercial = new javax.swing.JLabel();
        jPanelNinosPortalBosque = new javax.swing.JPanel();
        numNinosPortalBosque = new javax.swing.JLabel();
        jPanelNinosPortalLaboratorio3 = new javax.swing.JPanel();
        numCapturasColmena4 = new javax.swing.JLabel();
        jPanelNinosPortalAlcantarillado = new javax.swing.JPanel();
        numNinosPortalAlcantarillado = new javax.swing.JLabel();
        jPanelUpsideDown = new javax.swing.JPanel();
        SeresVivosEtc = new javax.swing.JLabel();
        Laboratorio1 = new javax.swing.JLabel();
        CentroComercial1 = new javax.swing.JLabel();
        Bosque1 = new javax.swing.JLabel();
        Alcantarillado1 = new javax.swing.JLabel();
        jPanelNinosLaboratorio = new javax.swing.JPanel();
        numNinosLaboratorio = new javax.swing.JLabel();
        jPanelNinosCentroComercial = new javax.swing.JPanel();
        numNinosCentroComercial = new javax.swing.JLabel();
        jPanelNinosBosque = new javax.swing.JPanel();
        numNinosBosque = new javax.swing.JLabel();
        jPanelNinosAlcantarillado = new javax.swing.JPanel();
        numNinosAlcantarillado = new javax.swing.JLabel();
        jPanelDemogLaboratorio = new javax.swing.JPanel();
        numDemogLaboratorio = new javax.swing.JLabel();
        jPanelDemogCentroComercial = new javax.swing.JPanel();
        numDemogCentroComercial = new javax.swing.JLabel();
        jPanelDemogBosque = new javax.swing.JPanel();
        numDemogBosque = new javax.swing.JLabel();
        jPanelDemogAlcantarillado = new javax.swing.JPanel();
        numDemogAlcantarillado = new javax.swing.JLabel();
        Colmena = new javax.swing.JLabel();
        jPanelColmena = new javax.swing.JPanel();
        numNinosCapturadosColmena = new javax.swing.JLabel();
        jPanelRankingCapturas = new javax.swing.JPanel();
        DemogorgonsConMayor = new javax.swing.JLabel();
        numeroDeCapturas = new javax.swing.JLabel();
        idPrimerDemog = new javax.swing.JLabel();
        idSegundoDemog = new javax.swing.JLabel();
        idTercerDemog = new javax.swing.JLabel();
        Primero = new javax.swing.JLabel();
        Segundo = new javax.swing.JLabel();
        Tercero = new javax.swing.JLabel();
        jPanelCapturasDemog1 = new javax.swing.JPanel();
        numCapturasPrimerDemog = new javax.swing.JLabel();
        jPanelCapturasDemog2 = new javax.swing.JPanel();
        jPanelNinosPortalLaboratorio4 = new javax.swing.JPanel();
        numCapturasColmena5 = new javax.swing.JLabel();
        numCapturasSegundoDemog = new javax.swing.JLabel();
        jPanelCapturasDemog3 = new javax.swing.JPanel();
        numCapturasTercerDemog = new javax.swing.JLabel();
        jPanelEventos = new javax.swing.JPanel();
        jPanelSegundosRestantes = new javax.swing.JPanel();
        segsRestantesEvento = new javax.swing.JLabel();
        TiempoRestante = new javax.swing.JLabel();
        jPanelEventoActual = new javax.swing.JPanel();
        eventoActivo = new javax.swing.JLabel();
        BotonDeControl = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hawkins.setFont(new java.awt.Font("Yatra One", 1, 36)); // NOI18N
        Hawkins.setForeground(new java.awt.Color(155, 0, 50));
        Hawkins.setText("Hawkins");
        add(Hawkins, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 40));

        Portales.setFont(new java.awt.Font("Yatra One", 1, 36)); // NOI18N
        Portales.setForeground(new java.awt.Color(155, 0, 50));
        Portales.setText("Portales");
        add(Portales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 40));

        UpsideDown.setFont(new java.awt.Font("Yatra One", 1, 36)); // NOI18N
        UpsideDown.setForeground(new java.awt.Color(155, 0, 50));
        UpsideDown.setText("Upside Down");
        add(UpsideDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 510, 40));

        Capturas.setFont(new java.awt.Font("Yatra One", 1, 36)); // NOI18N
        Capturas.setForeground(new java.awt.Color(155, 0, 50));
        Capturas.setText("Capturas");
        add(Capturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 310, 40));

        EventoActual.setFont(new java.awt.Font("Yatra One", 1, 36)); // NOI18N
        EventoActual.setForeground(new java.awt.Color(155, 0, 50));
        EventoActual.setText("Evento actual");
        add(EventoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 310, 40));

        jPanelHawkins.setBackground(new java.awt.Color(38, 0, 0));
        jPanelHawkins.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(155, 0, 50), 3, true));
        jPanelHawkins.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NinosEnHawkins.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        NinosEnHawkins.setForeground(new java.awt.Color(204, 0, 0));
        NinosEnHawkins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NinosEnHawkins.setText("Niños en Hawkins");
        jPanelHawkins.add(NinosEnHawkins, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 310, -1));

        jPanelNinosHawkins.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosHawkins.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosHawkins.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosHawkins.setForeground(new java.awt.Color(255, 255, 255));
        numNinosHawkins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosHawkins.setText("-");
        numNinosHawkins.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosHawkins.add(numNinosHawkins, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 60));

        jPanelHawkins.add(jPanelNinosHawkins, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, -1));

        add(jPanelHawkins, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 140));

        jPanelPortales.setBackground(new java.awt.Color(38, 0, 0));
        jPanelPortales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(155, 0, 50), 3, true));
        jPanelPortales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EstadoActual.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        EstadoActual.setForeground(new java.awt.Color(204, 0, 0));
        EstadoActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstadoActual.setText("Estado actual");
        jPanelPortales.add(EstadoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, -1));

        Laboratorio.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        Laboratorio.setForeground(new java.awt.Color(204, 0, 0));
        Laboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Laboratorio.setText("Laboratorio");
        jPanelPortales.add(Laboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 40));

        CentroComercial.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        CentroComercial.setForeground(new java.awt.Color(204, 0, 0));
        CentroComercial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CentroComercial.setText("Centro Comercial");
        jPanelPortales.add(CentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 40));

        Bosque.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        Bosque.setForeground(new java.awt.Color(204, 0, 0));
        Bosque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bosque.setText("Bosque");
        jPanelPortales.add(Bosque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 40));

        Alcantarillado.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        Alcantarillado.setForeground(new java.awt.Color(204, 0, 0));
        Alcantarillado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alcantarillado.setText("Alcantarillado");
        jPanelPortales.add(Alcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 40));

        jPanelNinosPortalLaboratorio.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosPortalLaboratorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosPortalLaboratorio.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosPortalLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        numNinosPortalLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosPortalLaboratorio.setText("- niños");
        numNinosPortalLaboratorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosPortalLaboratorio.add(numNinosPortalLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelPortales.add(jPanelNinosPortalLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 110, 40));

        jPanelNinosPortalCentroComercial.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosPortalCentroComercial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosPortalCentroComercial.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosPortalCentroComercial.setForeground(new java.awt.Color(255, 255, 255));
        numNinosPortalCentroComercial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosPortalCentroComercial.setText("- niños");
        numNinosPortalCentroComercial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosPortalCentroComercial.add(numNinosPortalCentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelPortales.add(jPanelNinosPortalCentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, 40));

        jPanelNinosPortalBosque.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosPortalBosque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosPortalBosque.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosPortalBosque.setForeground(new java.awt.Color(255, 255, 255));
        numNinosPortalBosque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosPortalBosque.setText("- niños");
        numNinosPortalBosque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosPortalBosque.add(numNinosPortalBosque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelNinosPortalLaboratorio3.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosPortalLaboratorio3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numCapturasColmena4.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numCapturasColmena4.setForeground(new java.awt.Color(255, 255, 255));
        numCapturasColmena4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCapturasColmena4.setText("- niños");
        numCapturasColmena4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosPortalLaboratorio3.add(numCapturasColmena4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 30));

        jPanelNinosPortalBosque.add(jPanelNinosPortalLaboratorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, 40));

        jPanelPortales.add(jPanelNinosPortalBosque, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 110, 40));

        jPanelNinosPortalAlcantarillado.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosPortalAlcantarillado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosPortalAlcantarillado.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosPortalAlcantarillado.setForeground(new java.awt.Color(255, 255, 255));
        numNinosPortalAlcantarillado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosPortalAlcantarillado.setText("- niños");
        numNinosPortalAlcantarillado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosPortalAlcantarillado.add(numNinosPortalAlcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelPortales.add(jPanelNinosPortalAlcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, 40));

        add(jPanelPortales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 310, 290));

        jPanelUpsideDown.setBackground(new java.awt.Color(38, 0, 0));
        jPanelUpsideDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(155, 0, 50), 3, true));
        jPanelUpsideDown.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeresVivosEtc.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        SeresVivosEtc.setForeground(new java.awt.Color(204, 0, 0));
        SeresVivosEtc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeresVivosEtc.setText("Seres vivos detectados en las ubicaciones");
        jPanelUpsideDown.add(SeresVivosEtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 510, -1));

        Laboratorio1.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        Laboratorio1.setForeground(new java.awt.Color(204, 0, 0));
        Laboratorio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Laboratorio1.setText("Laboratorio");
        jPanelUpsideDown.add(Laboratorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 190, 40));

        CentroComercial1.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        CentroComercial1.setForeground(new java.awt.Color(204, 0, 0));
        CentroComercial1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CentroComercial1.setText("Centro Comercial");
        jPanelUpsideDown.add(CentroComercial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 40));

        Bosque1.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        Bosque1.setForeground(new java.awt.Color(204, 0, 0));
        Bosque1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bosque1.setText("Bosque");
        jPanelUpsideDown.add(Bosque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 40));

        Alcantarillado1.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        Alcantarillado1.setForeground(new java.awt.Color(204, 0, 0));
        Alcantarillado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alcantarillado1.setText("Alcantarillado");
        jPanelUpsideDown.add(Alcantarillado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 40));

        jPanelNinosLaboratorio.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosLaboratorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosLaboratorio.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        numNinosLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosLaboratorio.setText("- niños");
        numNinosLaboratorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosLaboratorio.add(numNinosLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelUpsideDown.add(jPanelNinosLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 110, 40));

        jPanelNinosCentroComercial.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosCentroComercial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosCentroComercial.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosCentroComercial.setForeground(new java.awt.Color(255, 255, 255));
        numNinosCentroComercial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosCentroComercial.setText("- niños");
        numNinosCentroComercial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosCentroComercial.add(numNinosCentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelUpsideDown.add(jPanelNinosCentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, 40));

        jPanelNinosBosque.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosBosque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosBosque.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosBosque.setForeground(new java.awt.Color(255, 255, 255));
        numNinosBosque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosBosque.setText("- niños");
        numNinosBosque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosBosque.add(numNinosBosque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelUpsideDown.add(jPanelNinosBosque, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 110, 40));

        jPanelNinosAlcantarillado.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosAlcantarillado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosAlcantarillado.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosAlcantarillado.setForeground(new java.awt.Color(255, 255, 255));
        numNinosAlcantarillado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosAlcantarillado.setText("- niños");
        numNinosAlcantarillado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosAlcantarillado.add(numNinosAlcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelUpsideDown.add(jPanelNinosAlcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 110, 40));

        jPanelDemogLaboratorio.setBackground(new java.awt.Color(155, 0, 50));
        jPanelDemogLaboratorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numDemogLaboratorio.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numDemogLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        numDemogLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numDemogLaboratorio.setText("- demogorgons");
        numDemogLaboratorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelDemogLaboratorio.add(numDemogLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanelUpsideDown.add(jPanelDemogLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 160, 40));

        jPanelDemogCentroComercial.setBackground(new java.awt.Color(155, 0, 50));
        jPanelDemogCentroComercial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numDemogCentroComercial.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numDemogCentroComercial.setForeground(new java.awt.Color(255, 255, 255));
        numDemogCentroComercial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numDemogCentroComercial.setText("- demogorgons");
        numDemogCentroComercial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelDemogCentroComercial.add(numDemogCentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanelUpsideDown.add(jPanelDemogCentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 160, 40));

        jPanelDemogBosque.setBackground(new java.awt.Color(155, 0, 50));
        jPanelDemogBosque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numDemogBosque.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numDemogBosque.setForeground(new java.awt.Color(255, 255, 255));
        numDemogBosque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numDemogBosque.setText("- demogorgons");
        numDemogBosque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelDemogBosque.add(numDemogBosque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanelUpsideDown.add(jPanelDemogBosque, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 160, 40));

        jPanelDemogAlcantarillado.setBackground(new java.awt.Color(155, 0, 50));
        jPanelDemogAlcantarillado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numDemogAlcantarillado.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numDemogAlcantarillado.setForeground(new java.awt.Color(255, 255, 255));
        numDemogAlcantarillado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numDemogAlcantarillado.setText("- demogorgons");
        numDemogAlcantarillado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelDemogAlcantarillado.add(numDemogAlcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 40));

        jPanelUpsideDown.add(jPanelDemogAlcantarillado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 160, 40));

        Colmena.setFont(new java.awt.Font("Yatra One", 1, 24)); // NOI18N
        Colmena.setForeground(new java.awt.Color(155, 0, 50));
        Colmena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Colmena.setText("Capturados en colmena");
        jPanelUpsideDown.add(Colmena, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 330, 40));

        jPanelColmena.setBackground(new java.awt.Color(155, 0, 50));
        jPanelColmena.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numNinosCapturadosColmena.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numNinosCapturadosColmena.setForeground(new java.awt.Color(255, 255, 255));
        numNinosCapturadosColmena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numNinosCapturadosColmena.setText("- niños");
        numNinosCapturadosColmena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelColmena.add(numNinosCapturadosColmena, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jPanelUpsideDown.add(jPanelColmena, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 110, 40));

        add(jPanelUpsideDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 500, 380));

        jPanelRankingCapturas.setBackground(new java.awt.Color(38, 0, 0));
        jPanelRankingCapturas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(155, 0, 50), 3, true));
        jPanelRankingCapturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DemogorgonsConMayor.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        DemogorgonsConMayor.setForeground(new java.awt.Color(204, 0, 0));
        DemogorgonsConMayor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DemogorgonsConMayor.setText("Demogorgons con mayor");
        jPanelRankingCapturas.add(DemogorgonsConMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 310, -1));

        numeroDeCapturas.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numeroDeCapturas.setForeground(new java.awt.Color(204, 0, 0));
        numeroDeCapturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroDeCapturas.setText("número de capturas");
        jPanelRankingCapturas.add(numeroDeCapturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 310, -1));

        idPrimerDemog.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        idPrimerDemog.setForeground(new java.awt.Color(204, 0, 0));
        idPrimerDemog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idPrimerDemog.setText("N0000");
        jPanelRankingCapturas.add(idPrimerDemog, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 40));

        idSegundoDemog.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        idSegundoDemog.setForeground(new java.awt.Color(204, 0, 0));
        idSegundoDemog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idSegundoDemog.setText("-");
        jPanelRankingCapturas.add(idSegundoDemog, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 40));

        idTercerDemog.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        idTercerDemog.setForeground(new java.awt.Color(204, 0, 0));
        idTercerDemog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idTercerDemog.setText("-");
        jPanelRankingCapturas.add(idTercerDemog, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 90, 40));

        Primero.setFont(new java.awt.Font("Yatra One", 1, 24)); // NOI18N
        Primero.setForeground(new java.awt.Color(204, 0, 0));
        Primero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Primero.setText("1:");
        jPanelRankingCapturas.add(Primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, 40));

        Segundo.setFont(new java.awt.Font("Yatra One", 1, 24)); // NOI18N
        Segundo.setForeground(new java.awt.Color(204, 0, 0));
        Segundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Segundo.setText("2:");
        jPanelRankingCapturas.add(Segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, 40));

        Tercero.setFont(new java.awt.Font("Yatra One", 1, 24)); // NOI18N
        Tercero.setForeground(new java.awt.Color(204, 0, 0));
        Tercero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tercero.setText("3:");
        jPanelRankingCapturas.add(Tercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 40, 40));

        jPanelCapturasDemog1.setBackground(new java.awt.Color(155, 0, 50));
        jPanelCapturasDemog1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numCapturasPrimerDemog.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numCapturasPrimerDemog.setForeground(new java.awt.Color(255, 255, 255));
        numCapturasPrimerDemog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCapturasPrimerDemog.setText("- capturas");
        numCapturasPrimerDemog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelCapturasDemog1.add(numCapturasPrimerDemog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        jPanelRankingCapturas.add(jPanelCapturasDemog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, 40));

        jPanelCapturasDemog2.setBackground(new java.awt.Color(155, 0, 50));
        jPanelCapturasDemog2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNinosPortalLaboratorio4.setBackground(new java.awt.Color(155, 0, 50));
        jPanelNinosPortalLaboratorio4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numCapturasColmena5.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numCapturasColmena5.setForeground(new java.awt.Color(255, 255, 255));
        numCapturasColmena5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCapturasColmena5.setText("- niños");
        numCapturasColmena5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelNinosPortalLaboratorio4.add(numCapturasColmena5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 30));

        jPanelCapturasDemog2.add(jPanelNinosPortalLaboratorio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, 40));

        numCapturasSegundoDemog.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numCapturasSegundoDemog.setForeground(new java.awt.Color(255, 255, 255));
        numCapturasSegundoDemog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCapturasSegundoDemog.setText("- capturas");
        numCapturasSegundoDemog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelCapturasDemog2.add(numCapturasSegundoDemog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        jPanelRankingCapturas.add(jPanelCapturasDemog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 40));

        jPanelCapturasDemog3.setBackground(new java.awt.Color(155, 0, 50));
        jPanelCapturasDemog3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numCapturasTercerDemog.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        numCapturasTercerDemog.setForeground(new java.awt.Color(255, 255, 255));
        numCapturasTercerDemog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numCapturasTercerDemog.setText("- capturas");
        numCapturasTercerDemog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelCapturasDemog3.add(numCapturasTercerDemog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        jPanelRankingCapturas.add(jPanelCapturasDemog3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 130, 40));

        add(jPanelRankingCapturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 310, 270));

        jPanelEventos.setBackground(new java.awt.Color(38, 0, 0));
        jPanelEventos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(155, 0, 50), 3, true));
        jPanelEventos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSegundosRestantes.setBackground(new java.awt.Color(155, 0, 50));
        jPanelSegundosRestantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        segsRestantesEvento.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        segsRestantesEvento.setForeground(new java.awt.Color(255, 255, 255));
        segsRestantesEvento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segsRestantesEvento.setText("- seg");
        segsRestantesEvento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelSegundosRestantes.add(segsRestantesEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        jPanelEventos.add(jPanelSegundosRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 90, 50));

        TiempoRestante.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        TiempoRestante.setForeground(new java.awt.Color(204, 0, 0));
        TiempoRestante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TiempoRestante.setText("Tiempo restante: ");
        jPanelEventos.add(TiempoRestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 50));

        jPanelEventoActual.setBackground(new java.awt.Color(155, 0, 50));
        jPanelEventoActual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventoActivo.setFont(new java.awt.Font("Yatra One", 1, 18)); // NOI18N
        eventoActivo.setForeground(new java.awt.Color(255, 255, 255));
        eventoActivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventoActivo.setText("Ningún evento activo");
        eventoActivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        jPanelEventoActual.add(eventoActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 50));

        jPanelEventos.add(jPanelEventoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, -1));

        add(jPanelEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 310, 160));

        BotonDeControl.setBackground(new java.awt.Color(155, 0, 50));
        BotonDeControl.setFont(new java.awt.Font("Yatra One", 1, 36)); // NOI18N
        BotonDeControl.setForeground(new java.awt.Color(255, 255, 255));
        BotonDeControl.setText("PAUSAR SIMULACIÓN");
        BotonDeControl.setToolTipText("");
        BotonDeControl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        BotonDeControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonDeControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonDeControlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonDeControlMouseExited(evt);
            }
        });
        add(BotonDeControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 500, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -50, 1340, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDeControlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDeControlMouseEntered
        BotonDeControl.setBackground(new Color(200,0,50));
    }//GEN-LAST:event_BotonDeControlMouseEntered

    private void BotonDeControlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDeControlMouseExited
        BotonDeControl.setBackground(new Color(155,0,50));
    }//GEN-LAST:event_BotonDeControlMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alcantarillado;
    private javax.swing.JLabel Alcantarillado1;
    private javax.swing.JLabel Bosque;
    private javax.swing.JLabel Bosque1;
    private javax.swing.JButton BotonDeControl;
    private javax.swing.JLabel Capturas;
    private javax.swing.JLabel CentroComercial;
    private javax.swing.JLabel CentroComercial1;
    private javax.swing.JLabel Colmena;
    private javax.swing.JLabel DemogorgonsConMayor;
    private javax.swing.JLabel EstadoActual;
    private javax.swing.JLabel EventoActual;
    private javax.swing.JLabel Hawkins;
    private javax.swing.JLabel Laboratorio;
    private javax.swing.JLabel Laboratorio1;
    private javax.swing.JLabel NinosEnHawkins;
    private javax.swing.JLabel Portales;
    private javax.swing.JLabel Primero;
    private javax.swing.JLabel Segundo;
    private javax.swing.JLabel SeresVivosEtc;
    private javax.swing.JLabel Tercero;
    private javax.swing.JLabel TiempoRestante;
    private javax.swing.JLabel UpsideDown;
    private javax.swing.JLabel background;
    private javax.swing.JLabel eventoActivo;
    private javax.swing.JLabel idPrimerDemog;
    private javax.swing.JLabel idSegundoDemog;
    private javax.swing.JLabel idTercerDemog;
    private javax.swing.JPanel jPanelCapturasDemog1;
    private javax.swing.JPanel jPanelCapturasDemog2;
    private javax.swing.JPanel jPanelCapturasDemog3;
    private javax.swing.JPanel jPanelColmena;
    private javax.swing.JPanel jPanelDemogAlcantarillado;
    private javax.swing.JPanel jPanelDemogBosque;
    private javax.swing.JPanel jPanelDemogCentroComercial;
    private javax.swing.JPanel jPanelDemogLaboratorio;
    private javax.swing.JPanel jPanelEventoActual;
    private javax.swing.JPanel jPanelEventos;
    private javax.swing.JPanel jPanelHawkins;
    private javax.swing.JPanel jPanelNinosAlcantarillado;
    private javax.swing.JPanel jPanelNinosBosque;
    private javax.swing.JPanel jPanelNinosCentroComercial;
    private javax.swing.JPanel jPanelNinosHawkins;
    private javax.swing.JPanel jPanelNinosLaboratorio;
    private javax.swing.JPanel jPanelNinosPortalAlcantarillado;
    private javax.swing.JPanel jPanelNinosPortalBosque;
    private javax.swing.JPanel jPanelNinosPortalCentroComercial;
    private javax.swing.JPanel jPanelNinosPortalLaboratorio;
    private javax.swing.JPanel jPanelNinosPortalLaboratorio3;
    private javax.swing.JPanel jPanelNinosPortalLaboratorio4;
    private javax.swing.JPanel jPanelPortales;
    private javax.swing.JPanel jPanelRankingCapturas;
    private javax.swing.JPanel jPanelSegundosRestantes;
    private javax.swing.JPanel jPanelUpsideDown;
    private javax.swing.JLabel numCapturasColmena4;
    private javax.swing.JLabel numCapturasColmena5;
    private javax.swing.JLabel numCapturasPrimerDemog;
    private javax.swing.JLabel numCapturasSegundoDemog;
    private javax.swing.JLabel numCapturasTercerDemog;
    private javax.swing.JLabel numDemogAlcantarillado;
    private javax.swing.JLabel numDemogBosque;
    private javax.swing.JLabel numDemogCentroComercial;
    private javax.swing.JLabel numDemogLaboratorio;
    private javax.swing.JLabel numNinosAlcantarillado;
    private javax.swing.JLabel numNinosBosque;
    private javax.swing.JLabel numNinosCapturadosColmena;
    private javax.swing.JLabel numNinosCentroComercial;
    private javax.swing.JLabel numNinosHawkins;
    private javax.swing.JLabel numNinosLaboratorio;
    private javax.swing.JLabel numNinosPortalAlcantarillado;
    private javax.swing.JLabel numNinosPortalBosque;
    private javax.swing.JLabel numNinosPortalCentroComercial;
    private javax.swing.JLabel numNinosPortalLaboratorio;
    private javax.swing.JLabel numeroDeCapturas;
    private javax.swing.JLabel segsRestantesEvento;
    // End of variables declaration//GEN-END:variables
}
